import 'package:flutter/material.dart';
import 'package:flutterapp/vendingmachineapp/generatedpaymentwidget/generated/GeneratedChooseapaymentmethodWidget.dart';
import 'package:flutterapp/vendingmachineapp/generatedpaymentwidget/generated/GeneratedButton_OtherPaymentWidget.dart';
import 'package:flutterapp/vendingmachineapp/generatedpaymentwidget/generated/GeneratedButton_RevolutWidget.dart';
import 'package:flutterapp/vendingmachineapp/generatedpaymentwidget/generated/GeneratedLabel_PaymentWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
          child: Container(
        width: 390.0,
        height: 844.0,
            child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.25,
                top: -0.2249755859375,
                right: 0.0,
                bottom: null,
                width: null,
                height: 85.0,
                child: GeneratedLabel_PaymentWidget(),
              ),
              Positioned(
                left: 39.0,
                top: null,
                right: 39.0,
                bottom: null,
                width: null,
                height: 62.04999923706055,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -135.98,
                    z: 0,
                    child: GeneratedButton_RevolutWidget()),
              ),
              Positioned(
                left: 39.0,
                top: null,
                right: 39.0,
                bottom: null,
                width: null,
                height: 62.04999923706055,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -53.98,
                    z: 0,
                    child: GeneratedButton_OtherPaymentWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 213.64999389648438,
                height: 50.45000076293945,
                child: TransformHelper.translate(
                    x: -0.18,
                    y: -247.77,
                    z: 0,
                    child: GeneratedChooseapaymentmethodWidget()),
              )
            ]),
      ),
    ));
  }
}
