import 'package:flutter/material.dart';
import 'package:flutterapp/Braintree/BraintreePay.dart';
import 'package:flutterapp/RevolutPayment/RevolutPay.dart';
import 'package:flutterapp/StripePayment/StripePay.dart';
import 'package:flutterapp/ThirdModule/ThirdModule.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

import '../../IPayment/PaymentInterface.dart';



/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    var paymentInterfaceList = <PaymentInterface>[
      RevolutPay(),
      BraintreePay(),
      StripePay(),
      ThirdModule()
    ];

    var paymentButtonList = <Widget>[];

    for (var paymentInterface in paymentInterfaceList) {
      paymentButtonList.add(
        Container(
          margin: EdgeInsets.only(top: 25),
          child: paymentInterface.getPayButton(context),
        )
      );
    }

    return Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text("Choose a payment method", style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold)),
          ...paymentButtonList
        ],
      ),
    );
  }
}
