import 'package:flutter/material.dart';
import 'package:flutterapp/vendingmachineapp/generatedqr_code_scanwidget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/vendingmachineapp/generatedqr_code_scanwidget/generated/GeneratedScantheQRcodeoftheproductwhichyouwanttotakeWidget.dart';

/* Frame QR_code_scan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQR_code_scanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.21957397460938,
                height: 73.0456771850586,
                child: TransformHelper.translate(
                    x: 1.11, y: -343.48, z: 0, child: GeneratedLogoWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 213.64999389648438,
                height: 50.45000076293945,
                child: TransformHelper.translate(
                    x: 0.82,
                    y: -240.77,
                    z: 0,
                    child:
                        GeneratedScantheQRcodeoftheproductwhichyouwanttotakeWidget()),
              )
            ]),
      ),
    ));
  }
}
