import 'package:flutter/material.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/TextBoxCity.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/RegistrationLabel.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/TextBoxFirstLastName.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/TextBoxPasswordRegistration.dart';

import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/TextBoxEmail.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/vendingmachineapp/generatedregistrationwidget/generated/ButtonSignup.dart';

/* Frame Registration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Container(
              width: 390.0,
              height: 844.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: null,
                      top: null,
                      right: null,
                      bottom: null,
                      width: 188.0,
                      height: 42.0,
                      child: TransformHelper.translate(
                          x: 2.00,
                          y: -246.00,
                          z: 0,
                          child: RegistrationLabel()),
                    ),
                    Positioned(
                      left: 25.0,
                      top: null,
                      right: 25.0,
                      bottom: null,
                      width: null,
                      height: 62.53499984741211,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: -159.73,
                          z: 0,
                          child: TextBoxFirstLastName()),
                    ),
                    Positioned(
                      left: 25.0,
                      top: null,
                      right: 25.0,
                      bottom: null,
                      width: null,
                      height: 62.53499984741211,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: -79.73,
                          z: 0,
                          child: TextBoxEmail()),
                    ),
                    Positioned(
                      left: 25.0,
                      top: null,
                      right: 25.0,
                      bottom: null,
                      width: null,
                      height: 62.53499984741211,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 0.27,
                          z: 0,
                          child: TextBoxPasswordRegistration()),
                    ),
                    Positioned(
                      left: 25.0,
                      top: null,
                      right: 25.0,
                      bottom: null,
                      width: null,
                      height: 62.53499984741211,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 80.27,
                          z: 0,
                          child: TextBoxCity()),
                    ),
                    Positioned(
                      left: 25.0,
                      top: null,
                      right: 25.0,
                      bottom: null,
                      width: null,
                      height: 62.53499984741211,
                      child: TransformHelper.translate(
                          x: 0.00,
                          y: 262.27,
                          z: 0,
                          child: ButtonSignup()),
                    )
                  ]),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 82.21957397460938,
              height: 73.0456771850586,
              child: TransformHelper.translate(
                  x: 1.11, y: -343.48, z: 0, child: GeneratedLogoWidget()),
            )
          ]),
    ));
  }
}
